spring.application.name=${APPLICATION_NAME}
server.servlet.context-path=/api/v1
server.forward-headers-strategy=native

springdoc.swagger-ui.defaultModelsExpandDepth=-1
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.datasource.url=${HOMOLOG_DB_URL}
spring.datasource.username=${HOMOLOG_DB_USERNAME}
spring.datasource.password=${HOMOLOG_DB_PASSWORD}

server.port=${HOMOLOG_SERVER_PORT}
api.security.token.secret=${HOMOLOG_JWT_SECRET}

spring.docker.compose.enabled=true
spring.docker.compose.profiles=homolog
spring.docker.compose.file=docker-compose.yml
